---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)

#load additional packages
library(tidyverse)
library(viridis)
## Loading required package: viridisLite
library(p8105.datasets)
library(plotly)

#ran library(shiny) in console in order to access the help bar. runtime: shiny automatically loads the package
```


```{r}
data(nyc_airbnb)

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |>
  select(
    borough = neighbourhood_group, neighbourhood, stars, price, room_type,
    lat, long) 
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
#DROP DOWN
boroughs = nyc_airbnb |> distinct(borough) |> pull()

selectInput(
  inputId = "borough_choice",
  label = h3("Select Borough"), #h3 is just the header type, you could choose h2 or something else
  choices = boroughs,
  selected = "Manhattan" #default selected value #WHY IS THIS NOT WORKING
)


```


```{r}
#SLIDER BAR
min_price = nyc_airbnb |> pull(price) |> min()
max_price = nyc_airbnb |> pull(price) |> max()

sliderInput(
  inputId = "price_range", 
  label = h3("Choose price range"), 
  min = min_price, 
  max = max_price, 
  value = c(100, 400))
```

```{r}
#RADIO BUTTONS

room_choice = nyc_airbnb |> distinct(room_type) |> pull()

# radioButtons widget
radioButtons(
  "room_choice", 
  label = h3("Choose room type"),
  choices = room_choice, selected = "Entire home/apt")
```



Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

renderPlotly(
nyc_airbnb |> 
  filter(borough == input[["borough_choice"]], #2 means pulling out the smaller value 
         price <= input[["price_range"]][2],
         price >= input[["price_range"]][1],
         room_type == input[["room_choice"]]
         ) |> 
  plot_ly(
    x = ~long, y = ~lat, color = ~price,
    type = "scatter", mode = "markers"
        )
)



# input only works as a shiny app, so you cannot run it separately to debug

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

renderPlotly(
  nyc_airbnb |> 
      filter(borough == input[["borough_choice"]], #2 means pulling out the smaller value 
         price <= input[["price_range"]][2],
         price >= input[["price_range"]][1],
         room_type == input[["room_choice"]]
         ) |> 
    count(neighbourhood) |> 
    mutate(neighbourhood = fct_reorder(neighbourhood, n)) |> 
    plot_ly(x = ~neighbourhood, y = ~n, type = "bar")
)

```

### Chart C

```{r}
renderPlotly(
  nyc_airbnb |> 
         filter(borough == input[["borough_choice"]], #2 means pulling out the smaller value 
         price <= input[["price_range"]][2],
         price >= input[["price_range"]][1],
         room_type == input[["room_choice"]]
         ) |> 
    mutate(neighbourhood = fct_reorder(neighbourhood, price)) |> 
    plot_ly(x = ~neighbourhood, y = ~ price, type = "box")
)


   
```

